//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleBol.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleBol.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://amazon.com.
        /// </summary>
        internal static string AmazonUrl {
            get {
                return ResourceManager.GetString("AmazonUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\appSettings.json.
        /// </summary>
        internal static string AppSettingsJsonPath {
            get {
                return ResourceManager.GetString("AppSettingsJsonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\appSettings.bak.
        /// </summary>
        internal static string AppSettingsJsonPath_BU {
            get {
                return ResourceManager.GetString("AppSettingsJsonPath_BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Back32 {
            get {
                object obj = ResourceManager.GetObject("Back32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap badgeBol150 {
            get {
                object obj = ResourceManager.GetObject("badgeBol150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap badgeBolDispute150 {
            get {
                object obj = ResourceManager.GetObject("badgeBolDispute150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap badgeShippers150 {
            get {
                object obj = ResourceManager.GetObject("badgeShippers150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bolDefault250 {
            get {
                object obj = ResourceManager.GetObject("bolDefault250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bolProfessional250 {
            get {
                object obj = ResourceManager.GetObject("bolProfessional250", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bt_back {
            get {
                object obj = ResourceManager.GetObject("bt_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bt_back_20x20 {
            get {
                object obj = ResourceManager.GetObject("bt_back_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bt_back_36 {
            get {
                object obj = ResourceManager.GetObject("bt_back_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bt_powerOff {
            get {
                object obj = ResourceManager.GetObject("bt_powerOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btCreateBol {
            get {
                object obj = ResourceManager.GetObject("btCreateBol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BtDistribution {
            get {
                object obj = ResourceManager.GetObject("BtDistribution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btShippers {
            get {
                object obj = ResourceManager.GetObject("btShippers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Collapse28 {
            get {
                object obj = ResourceManager.GetObject("Collapse28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CollapseExpand28 {
            get {
                object obj = ResourceManager.GetObject("CollapseExpand28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CustomersIcon {
            get {
                object obj = ResourceManager.GetObject("CustomersIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataAcquisitionIcon {
            get {
                object obj = ResourceManager.GetObject("DataAcquisitionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataViewStockIcon {
            get {
                object obj = ResourceManager.GetObject("DataViewStockIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DbConnection {
            get {
                return ResourceManager.GetString("DbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Email2Icon {
            get {
                object obj = ResourceManager.GetObject("Email2Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmailIcon {
            get {
                object obj = ResourceManager.GetObject("EmailIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorIcon {
            get {
                object obj = ResourceManager.GetObject("ErrorIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExcelIcon {
            get {
                object obj = ResourceManager.GetObject("ExcelIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Expand28 {
            get {
                object obj = ResourceManager.GetObject("Expand28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExpandCollapse28 {
            get {
                object obj = ResourceManager.GetObject("ExpandCollapse28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FreightClassCodesIcon150 {
            get {
                object obj = ResourceManager.GetObject("FreightClassCodesIcon150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LicenseCode {
            get {
                return ResourceManager.GetString("LicenseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoBadge {
            get {
                object obj = ResourceManager.GetObject("logoBadge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to simpleBolDb.
        /// </summary>
        internal static string MongoDbDatabase {
            get {
                return ResourceManager.GetString("MongoDbDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\MongoDB\Data.
        /// </summary>
        internal static string MongoDbDataPath {
            get {
                return ResourceManager.GetString("MongoDbDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-ssl-4.0.4-signed.msi.
        /// </summary>
        internal static string MongoDBDownloadUrl {
            get {
                return ResourceManager.GetString("MongoDBDownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mongodb-win32-x86_64-2008plus-ssl-4.0.4-signed.msi.
        /// </summary>
        internal static string MongoDbFileName {
            get {
                return ResourceManager.GetString("MongoDbFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localhost.
        /// </summary>
        internal static string MongoDbHostName {
            get {
                return ResourceManager.GetString("MongoDbHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\MongoDB\Server\4.0\.
        /// </summary>
        internal static string MongoDbInstall {
            get {
                return ResourceManager.GetString("MongoDbInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\MongoDB\Server\4.0\.
        /// </summary>
        internal static string MongoDbInstallPath {
            get {
                return ResourceManager.GetString("MongoDbInstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\MongoDB\Logs.
        /// </summary>
        internal static string MongoDbLogsPath {
            get {
                return ResourceManager.GetString("MongoDbLogsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27017.
        /// </summary>
        internal static string MongoDbPort {
            get {
                return ResourceManager.GetString("MongoDbPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mongoLogo {
            get {
                object obj = ResourceManager.GetObject("mongoLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NmfcCodesIcon150 {
            get {
                object obj = ResourceManager.GetObject("NmfcCodesIcon150", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap palletIcon65 {
            get {
                object obj = ResourceManager.GetObject("palletIcon65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\BolDocuments\.
        /// </summary>
        internal static string PathBolDocuments {
            get {
                return ResourceManager.GetString("PathBolDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\Downloads.
        /// </summary>
        internal static string PathDownloads {
            get {
                return ResourceManager.GetString("PathDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\ErrorLogs.
        /// </summary>
        internal static string PathErrorLogs {
            get {
                return ResourceManager.GetString("PathErrorLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\.
        /// </summary>
        internal static string PathMarketPlace {
            get {
                return ResourceManager.GetString("PathMarketPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\.
        /// </summary>
        internal static string PathSimpleBol {
            get {
                return ResourceManager.GetString("PathSimpleBol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrintIcon {
            get {
                object obj = ResourceManager.GetObject("PrintIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\printSettings.json.
        /// </summary>
        internal static string PrintSettingsJsonPath {
            get {
                return ResourceManager.GetString("PrintSettingsJsonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \SimpleBol\printSettings.bak.
        /// </summary>
        internal static string PrintSettingsJsonPath_BU {
            get {
                return ResourceManager.GetString("PrintSettingsJsonPath_BU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Projects {
            get {
                object obj = ResourceManager.GetObject("Projects", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ProjectsIcon {
            get {
                object obj = ResourceManager.GetObject("ProjectsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ProjectsReverseIcon {
            get {
                object obj = ResourceManager.GetObject("ProjectsReverseIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pushPin {
            get {
                object obj = ResourceManager.GetObject("pushPin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuotationIcon {
            get {
                object obj = ResourceManager.GetObject("QuotationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh24 {
            get {
                object obj = ResourceManager.GetObject("Refresh24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh32 {
            get {
                object obj = ResourceManager.GetObject("Refresh32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendError.exe.
        /// </summary>
        internal static string SendError {
            get {
                return ResourceManager.GetString("SendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SimpleBOLSplashHeader {
            get {
                object obj = ResourceManager.GetObject("SimpleBOLSplashHeader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SimpleBOLSplashHeaderV2 {
            get {
                object obj = ResourceManager.GetObject("SimpleBOLSplashHeaderV2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updateFlagOff65 {
            get {
                object obj = ResourceManager.GetObject("updateFlagOff65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updateFlagOn65 {
            get {
                object obj = ResourceManager.GetObject("updateFlagOn65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap utilitiesIcon {
            get {
                object obj = ResourceManager.GetObject("utilitiesIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap utilitiesIcon1 {
            get {
                object obj = ResourceManager.GetObject("utilitiesIcon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vendorsIcon65 {
            get {
                object obj = ResourceManager.GetObject("vendorsIcon65", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
